/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedConversasRouteImport } from './routes/_authed/conversas'
import { Route as AuthedConfigRouteImport } from './routes/_authed/config'
import { Route as AuthedEleitoresIndexRouteImport } from './routes/_authed/eleitores/index'
import { Route as AuthedAtendimentosIndexRouteImport } from './routes/_authed/atendimentos/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConversasRoute = AuthedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConfigRoute = AuthedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEleitoresIndexRoute = AuthedEleitoresIndexRouteImport.update({
  id: '/eleitores/',
  path: '/eleitores/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAtendimentosIndexRoute = AuthedAtendimentosIndexRouteImport.update({
  id: '/atendimentos/',
  path: '/atendimentos/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/config': typeof AuthedConfigRoute
  '/conversas': typeof AuthedConversasRoute
  '/atendimentos/': typeof AuthedAtendimentosIndexRoute
  '/eleitores/': typeof AuthedEleitoresIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/config': typeof AuthedConfigRoute
  '/conversas': typeof AuthedConversasRoute
  '/': typeof AuthedIndexRoute
  '/atendimentos': typeof AuthedAtendimentosIndexRoute
  '/eleitores': typeof AuthedEleitoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/config': typeof AuthedConfigRoute
  '/_authed/conversas': typeof AuthedConversasRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/atendimentos/': typeof AuthedAtendimentosIndexRoute
  '/_authed/eleitores/': typeof AuthedEleitoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/config'
    | '/conversas'
    | '/atendimentos/'
    | '/eleitores/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/config' | '/conversas' | '/' | '/atendimentos' | '/eleitores'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/config'
    | '/_authed/conversas'
    | '/_authed/'
    | '/_authed/atendimentos/'
    | '/_authed/eleitores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/conversas': {
      id: '/_authed/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthedConversasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/config': {
      id: '/_authed/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthedConfigRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/eleitores/': {
      id: '/_authed/eleitores/'
      path: '/eleitores'
      fullPath: '/eleitores/'
      preLoaderRoute: typeof AuthedEleitoresIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/atendimentos/': {
      id: '/_authed/atendimentos/'
      path: '/atendimentos'
      fullPath: '/atendimentos/'
      preLoaderRoute: typeof AuthedAtendimentosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedConfigRoute: typeof AuthedConfigRoute
  AuthedConversasRoute: typeof AuthedConversasRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAtendimentosIndexRoute: typeof AuthedAtendimentosIndexRoute
  AuthedEleitoresIndexRoute: typeof AuthedEleitoresIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConfigRoute: AuthedConfigRoute,
  AuthedConversasRoute: AuthedConversasRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAtendimentosIndexRoute: AuthedAtendimentosIndexRoute,
  AuthedEleitoresIndexRoute: AuthedEleitoresIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
